server:
  port: 9001
   
logging:
  path: /yk/logs/yk_cloud/baseplatform/
          
eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
  client:
#   register-with-eureka ：表示是否将自己注册到Eureka Server，默认为true。由于当前这个应用就是Eureka Server，故而设为false
    register-with-eureka: false
#   fetchRegistry ：表示是否从Eureka Server获取注册信息，默认为true。因为这是一个单点的Eureka Server，不需要同步其他的Eureka Server节点的数据，故而设为false。
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:${server.port}/eureka
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 30000