server:
  port: 9001
   
logging:
  path: /yk/logs/yk_cloud/baseplatform/

spring:
  zipkin:
    base-url: http://192.168.0.105:9005
  sleuth:
    sampler:
      percentage: 1.0
          
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enable-self-preservation: false