server:
  port: 9001
   
logging:
  path: /yk/logs/yk_cloud/baseplatform/
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: true

spring:
  zipkin:
    base-url: http://192.168.0.105:9005
  sleuth:
    sampler:
      percentage: 1.0
          
eureka:
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000