server:
  port: 9201

logging:
  path: /yk/logs/yk_cloud/api/

eureka:
  client:
    serviceUrl:
      defaultZone: http://${YK_DISCOVERY_SERVICE_HOST}:${YK_DISCOVERY_SERVICE_PORT}/eureka
  instance:
    preferIpAddress: true

feign:
  httpclient:
    enabled: true

ribbon:
  ConnectTimeout: 600000
  ReadTimeout: 600000
  eureka:
    enabled: true
    
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
          strategy: SEMAPHORE

security:
  ignored: /noauth/**,/swagger**
  basic:
    enabled: false
  oauth2:
    client:
      client-id: yk
      client-secret: secret
      access-token-uri: http://${YK_AUTH_SERVICE_HOST}:${YK_AUTH_SERVICE_PORT}/uaa/oauth/token
      grant-type: client_credentials
    resource:
      token-info-uri: http://${YK_AUTH_SERVICE_HOST}:${YK_AUTH_SERVICE_PORT}/uaa/oauth/check_token