server:
  port: 9202
   
logging:
  path: /yk/logs/yk_cloud/api/

security:
  basic:
    enabled: false
  ignored: /noauth/**, /swagger**
  
spring:
  data:
    elasticsearch:
      cluster-name: my-application
      cluster-nodes: 127.0.0.1:9300 
      repositories: 
        enabled: true