server:
  port: 9002
  http:
    multipart:
      max-file-size: 200Mb
      max-request-size: 2500Mb
      
logging:
  path: /yk/logs/yk_cloud/baseplatform/
                          
eureka:
  client:
    serviceUrl:
      defaultZone: http://${YK_DISCOVERY_SERVICE_HOST}:${YK_DISCOVERY_SERVICE_PORT}/eureka
  instance:
    preferIpAddress: true

security:
  oauth2:
    client:
      client-id: yk
      client-secret: secret
      access-token-uri: http://${YK_AUTH_SERVICE_HOST}:${YK_AUTH_SERVICE_PORT}/uaa/oauth/token
      grant-type: client_credentials
    resource:
      token-info-uri: http://${YK_AUTH_SERVICE_HOST}:${YK_AUTH_SERVICE_PORT}/uaa/oauth/check_token
  
zuul:
  # 默认信号量大小 100 按需加大信号量
  semaphore:
    max-semaphores: 1000
  # 关闭全局重试机制
  retryable: false
  ignored-headers: Access-Control-Allow-Credentials,Access-Control-Allow-Origin,Access-Control-Allow-Methods
  sensitive-headers: Cookie,Set-Cookie
  add-proxy-headers: true
  add-host-header: true
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  prefix: /ykcloud/api
  # 关闭默认路由
  ignored-services: '*'
  routes:
    auth: /auth/**
    demo-api: /demo-api/**