SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
--  Table structure for `SJ_BLOB_TRIGGERS`
-- ----------------------------
DROP TABLE IF EXISTS `SJ_BLOB_TRIGGERS`;
CREATE TABLE `SJ_BLOB_TRIGGERS` (
  `SCHED_NAME` varchar(120) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `TRIGGER_NAME` varchar(200) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `TRIGGER_GROUP` varchar(200) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `BLOB_DATA` blob,
  PRIMARY KEY (`SCHED_NAME`,`TRIGGER_NAME`,`TRIGGER_GROUP`),
  CONSTRAINT `qrtz_blob_triggers_ibfk_1` FOREIGN KEY (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`) REFERENCES `SJ_TRIGGERS` (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ----------------------------
--  Table structure for `SJ_CALENDARS`
-- ----------------------------
DROP TABLE IF EXISTS `SJ_CALENDARS`;
CREATE TABLE `SJ_CALENDARS` (
  `SCHED_NAME` varchar(120) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `CALENDAR_NAME` varchar(200) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `CALENDAR` blob NOT NULL,
  PRIMARY KEY (`SCHED_NAME`,`CALENDAR_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ----------------------------
--  Table structure for `SJ_CRON_JOB`
-- ----------------------------
DROP TABLE IF EXISTS `SJ_CRON_JOB`;
CREATE TABLE `SJ_CRON_JOB` (
  `ID` char(36) NOT NULL,
  `EXPRESSION` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_CJ_JOB_ID` FOREIGN KEY (`ID`) REFERENCES `SJ_JOB` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ----------------------------
--  Table structure for `SJ_CRON_TRIGGERS`
-- ----------------------------
DROP TABLE IF EXISTS `SJ_CRON_TRIGGERS`;
CREATE TABLE `SJ_CRON_TRIGGERS` (
  `SCHED_NAME` varchar(120) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `TRIGGER_NAME` varchar(200) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `TRIGGER_GROUP` varchar(200) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `CRON_EXPRESSION` varchar(200) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `TIME_ZONE_ID` varchar(80) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`SCHED_NAME`,`TRIGGER_NAME`,`TRIGGER_GROUP`),
  CONSTRAINT `qrtz_cron_triggers_ibfk_1` FOREIGN KEY (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`) REFERENCES `SJ_TRIGGERS` (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ----------------------------
--  Table structure for `SJ_FIRED_TRIGGERS`
-- ----------------------------
DROP TABLE IF EXISTS `SJ_FIRED_TRIGGERS`;
CREATE TABLE `SJ_FIRED_TRIGGERS` (
  `SCHED_NAME` varchar(120) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `ENTRY_ID` varchar(95) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `TRIGGER_NAME` varchar(200) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `TRIGGER_GROUP` varchar(200) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `INSTANCE_NAME` varchar(200) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `FIRED_TIME` bigint(13) NOT NULL,
  `SCHED_TIME` bigint(13) NOT NULL,
  `PRIORITY` int(11) NOT NULL,
  `STATE` varchar(16) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `JOB_NAME` varchar(200) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `JOB_GROUP` varchar(200) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `IS_NONCONCURRENT` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `REQUESTS_RECOVERY` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`SCHED_NAME`,`ENTRY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ----------------------------
--  Table structure for `SJ_GENERAL_JOB`
-- ----------------------------
DROP TABLE IF EXISTS `SJ_GENERAL_JOB`;
CREATE TABLE `SJ_GENERAL_JOB` (
  `ID` char(36) NOT NULL,
  `REPEAT_COUNT` int(11) DEFAULT '0' COMMENT '重复的次数',
  `REPEAT_INTERVAL` int(11) DEFAULT NULL COMMENT '重复的间隔',
  `REPEAT_UNIT` tinyint(4) DEFAULT NULL COMMENT '重复时间间隔单位，参考数据字典',
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_GJ_JOB_ID` FOREIGN KEY (`ID`) REFERENCES `SJ_JOB` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ----------------------------
--  Table structure for `SJ_JOB`
-- ----------------------------
DROP TABLE IF EXISTS `SJ_JOB`;
CREATE TABLE `SJ_JOB` (
  `ID` char(36) NOT NULL,
  `CODE` varchar(255) DEFAULT NULL COMMENT '任务编码',
  `NAME` varchar(255) DEFAULT NULL COMMENT '任务名称',
  `GROUP_NAME` varchar(255) DEFAULT NULL COMMENT '任务集名称',
  `DESCRIPTION` varchar(255) DEFAULT NULL COMMENT '任务描述',
  `FAIL_STRATEGY` tinyint(4) DEFAULT NULL COMMENT '失败策略，参考数据字典',
  `MIS_STRATEGY` tinyint(4) DEFAULT NULL COMMENT '错失策略，参考数据字典',
  `STATUS` tinyint(4) DEFAULT NULL COMMENT '任务的状态，参考数据字典',
  `TYPE` tinyint(4) DEFAULT NULL COMMENT '任务的类型，属于CRON JOB类型，还是普通任务类型，参考数据字典',
  `START_DATE` timestamp NULL DEFAULT NULL COMMENT '任务开始的限定时间',
  `END_DATE` timestamp NULL DEFAULT NULL COMMENT '任务结束的限定时间',
  `CREATOR_ID` char(36) DEFAULT NULL COMMENT '创建者的ID',
  `CREATE_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ----------------------------
--  Table structure for `SJ_JOB_ALARM_INFO`
-- ----------------------------
DROP TABLE IF EXISTS `SJ_JOB_ALARM_INFO`;
CREATE TABLE `SJ_JOB_ALARM_INFO` (
  `ID` char(36) NOT NULL,
  `JOB_ID` char(36) DEFAULT NULL COMMENT 'JOB.ID',
  `TYPE` tinyint(4) DEFAULT NULL COMMENT '告警方式，参考数据字典',
  `TARGET` varchar(128) DEFAULT NULL COMMENT '告警目标的电话，或者Email',
  `STATUS` tinyint(4) DEFAULT NULL COMMENT '任务的告警设置状态，参考数据字典',
  `MSG_TEMPLATE_ID` char(36) DEFAULT NULL COMMENT '任务的告警消息模板',
  `CREATE_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `JOB_ID` (`JOB_ID`),
  CONSTRAINT `FK_JAI_JOB_ID` FOREIGN KEY (`JOB_ID`) REFERENCES `SJ_JOB` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ----------------------------
--  Table structure for `SJ_JOB_ALARM_RECORD`
-- ----------------------------
DROP TABLE IF EXISTS `SJ_JOB_ALARM_RECORD`;
CREATE TABLE `SJ_JOB_ALARM_RECORD` (
  `ID` char(36) NOT NULL,
  `JOB_EXE_RECORD_ID` char(36) DEFAULT NULL,
  `JOB_ALARM_INFO_ID` char(36) DEFAULT NULL,
  `GW_MSG_ID` char(36) DEFAULT NULL COMMENT '消息网关回传的告警消息的ID',
  `STATUS` tinyint(4) DEFAULT NULL COMMENT '告警记录的状态，参考数据字典',
  `CREATE_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `JOB_EXE_RECORD_ID` (`JOB_EXE_RECORD_ID`),
  KEY `JOB_ALARM_INFO_ID` (`JOB_ALARM_INFO_ID`),
  CONSTRAINT `FK_JAR_EXE_RECORD_ID` FOREIGN KEY (`JOB_EXE_RECORD_ID`) REFERENCES `SJ_JOB_EXE_RECORD` (`ID`),
  CONSTRAINT `FK_JAR_JOB_ALARM_INFO_ID` FOREIGN KEY (`JOB_ALARM_INFO_ID`) REFERENCES `SJ_JOB_ALARM_INFO` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ----------------------------
--  Table structure for `SJ_JOB_DETAILS`
-- ----------------------------
DROP TABLE IF EXISTS `SJ_JOB_DETAILS`;
CREATE TABLE `SJ_JOB_DETAILS` (
  `SCHED_NAME` varchar(120) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `JOB_NAME` varchar(200) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `JOB_GROUP` varchar(200) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `DESCRIPTION` varchar(250) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `JOB_CLASS_NAME` varchar(250) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `IS_DURABLE` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `IS_NONCONCURRENT` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `IS_UPDATE_DATA` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `REQUESTS_RECOVERY` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `JOB_DATA` blob,
  PRIMARY KEY (`SCHED_NAME`,`JOB_NAME`,`JOB_GROUP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ----------------------------
--  Table structure for `SJ_JOB_EXE_INFO`
-- ----------------------------
DROP TABLE IF EXISTS `SJ_JOB_EXE_INFO`;
CREATE TABLE `SJ_JOB_EXE_INFO` (
  `ID` char(36) NOT NULL,
  `JOB_ID` char(36) DEFAULT NULL COMMENT 'JOB的ID',
  `TYPE` tinyint(4) DEFAULT NULL COMMENT '执行的类型，HTTP/MQ 参考数据字典',
  `TARGET` varchar(255) DEFAULT NULL COMMENT 'URL或者MQ的EXCHANGE',
  `EXE_MODE` varchar(128) DEFAULT NULL COMMENT '执行类型，HTTP METHOD或MQ的ROUTING KEY',
  `PARAM` text DEFAULT NULL COMMENT '执行参数，以JSON字符串存储',
  `CREATE_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `JOB_ID` (`JOB_ID`),
  CONSTRAINT `FK_JEI_JOB_ID` FOREIGN KEY (`JOB_ID`) REFERENCES `SJ_JOB` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ----------------------------
--  Table structure for `SJ_JOB_EXE_RECORD`
-- ----------------------------
DROP TABLE IF EXISTS `SJ_JOB_EXE_RECORD`;
CREATE TABLE `SJ_JOB_EXE_RECORD` (
  `ID` char(36) NOT NULL,
  `JOB_ID` char(36) DEFAULT NULL COMMENT 'JOB的ID',
  `STATUS` tinyint(4) DEFAULT NULL COMMENT '执行记录的状态，参考数据字典',
  `EXE_TIME` timestamp NULL DEFAULT NULL COMMENT '执行时间',
  `RESULT_CODE` varchar(32) DEFAULT NULL COMMENT '执行结果的结果码',
  `RESULT_CONTENT` varchar(500) DEFAULT NULL COMMENT '执行结果内容',
  `RESULT_DESC` varchar(255) DEFAULT NULL COMMENT '执行结果描述',
  `CREATE_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `JOB_ID` (`JOB_ID`),
  CONSTRAINT `FK_JER_JOB_ID` FOREIGN KEY (`JOB_ID`) REFERENCES `SJ_JOB` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ----------------------------
--  Table structure for `SJ_LOCKS`
-- ----------------------------
DROP TABLE IF EXISTS `SJ_LOCKS`;
CREATE TABLE `SJ_LOCKS` (
  `SCHED_NAME` varchar(120) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `LOCK_NAME` varchar(40) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  PRIMARY KEY (`SCHED_NAME`,`LOCK_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ----------------------------
--  Table structure for `SJ_PAUSED_TRIGGER_GRPS`
-- ----------------------------
DROP TABLE IF EXISTS `SJ_PAUSED_TRIGGER_GRPS`;
CREATE TABLE `SJ_PAUSED_TRIGGER_GRPS` (
  `SCHED_NAME` varchar(120) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `TRIGGER_GROUP` varchar(200) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  PRIMARY KEY (`SCHED_NAME`,`TRIGGER_GROUP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ----------------------------
--  Table structure for `SJ_SCHEDULER_STATE`
-- ----------------------------
DROP TABLE IF EXISTS `SJ_SCHEDULER_STATE`;
CREATE TABLE `SJ_SCHEDULER_STATE` (
  `SCHED_NAME` varchar(120) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `INSTANCE_NAME` varchar(200) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `LAST_CHECKIN_TIME` bigint(13) NOT NULL,
  `CHECKIN_INTERVAL` bigint(13) NOT NULL,
  PRIMARY KEY (`SCHED_NAME`,`INSTANCE_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ----------------------------
--  Table structure for `SJ_SIMPLE_TRIGGERS`
-- ----------------------------
DROP TABLE IF EXISTS `SJ_SIMPLE_TRIGGERS`;
CREATE TABLE `SJ_SIMPLE_TRIGGERS` (
  `SCHED_NAME` varchar(120) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `TRIGGER_NAME` varchar(200) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `TRIGGER_GROUP` varchar(200) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `REPEAT_COUNT` bigint(7) NOT NULL,
  `REPEAT_INTERVAL` bigint(12) NOT NULL,
  `TIMES_TRIGGERED` bigint(10) NOT NULL,
  PRIMARY KEY (`SCHED_NAME`,`TRIGGER_NAME`,`TRIGGER_GROUP`),
  CONSTRAINT `qrtz_simple_triggers_ibfk_1` FOREIGN KEY (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`) REFERENCES `SJ_TRIGGERS` (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ----------------------------
--  Table structure for `SJ_SIMPROP_TRIGGERS`
-- ----------------------------
DROP TABLE IF EXISTS `SJ_SIMPROP_TRIGGERS`;
CREATE TABLE `SJ_SIMPROP_TRIGGERS` (
  `SCHED_NAME` varchar(120) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `TRIGGER_NAME` varchar(200) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `TRIGGER_GROUP` varchar(200) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `STR_PROP_1` varchar(512) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `STR_PROP_2` varchar(512) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `STR_PROP_3` varchar(512) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `INT_PROP_1` int(11) DEFAULT NULL,
  `INT_PROP_2` int(11) DEFAULT NULL,
  `LONG_PROP_1` bigint(20) DEFAULT NULL,
  `LONG_PROP_2` bigint(20) DEFAULT NULL,
  `DEC_PROP_1` decimal(13,4) DEFAULT NULL,
  `DEC_PROP_2` decimal(13,4) DEFAULT NULL,
  `BOOL_PROP_1` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `BOOL_PROP_2` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`SCHED_NAME`,`TRIGGER_NAME`,`TRIGGER_GROUP`),
  CONSTRAINT `qrtz_simprop_triggers_ibfk_1` FOREIGN KEY (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`) REFERENCES `SJ_TRIGGERS` (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ----------------------------
--  Table structure for `SJ_TRIGGERS`
-- ----------------------------
DROP TABLE IF EXISTS `SJ_TRIGGERS`;
CREATE TABLE `SJ_TRIGGERS` (
  `SCHED_NAME` varchar(120) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `TRIGGER_NAME` varchar(200) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `TRIGGER_GROUP` varchar(200) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `JOB_NAME` varchar(200) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `JOB_GROUP` varchar(200) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `DESCRIPTION` varchar(250) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `NEXT_FIRE_TIME` bigint(13) DEFAULT NULL,
  `PREV_FIRE_TIME` bigint(13) DEFAULT NULL,
  `PRIORITY` int(11) DEFAULT NULL,
  `TRIGGER_STATE` varchar(16) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `TRIGGER_TYPE` varchar(8) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `START_TIME` bigint(13) NOT NULL,
  `END_TIME` bigint(13) DEFAULT NULL,
  `CALENDAR_NAME` varchar(200) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `MISFIRE_INSTR` smallint(2) DEFAULT NULL,
  `JOB_DATA` blob,
  PRIMARY KEY (`SCHED_NAME`,`TRIGGER_NAME`,`TRIGGER_GROUP`),
  KEY `SCHED_NAME` (`SCHED_NAME`,`JOB_NAME`,`JOB_GROUP`),
  CONSTRAINT `qrtz_triggers_ibfk_1` FOREIGN KEY (`SCHED_NAME`, `JOB_NAME`, `JOB_GROUP`) REFERENCES `SJ_JOB_DETAILS` (`SCHED_NAME`, `JOB_NAME`, `JOB_GROUP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

SET FOREIGN_KEY_CHECKS = 1;