server:
  port: 9005

logging:
  path: /yk/logs/yk_cloud/baseplatform/

eureka:
  client:
    serviceUrl:
      defaultZone: http://${YK_DISCOVERY_SRV1_SERVICE_HOST}:${YK_DISCOVERY_SRV1_SERVICE_PORT}/eureka
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30