server:
  port: 9003

logging:
  path: /yk/logs/yk_cloud/baseplatform/

eureka:
  client:
    serviceUrl:
      defaultZone: http://${YK_DISCOVERY_SERVICE_HOST}:${YK_DISCOVERY_SERVICE_PORT}/eureka
  instance:
    preferIpAddress: true
    
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yk1001/yk-config.git