server:
  port: 9003

logging:
  path: /yk/logs/yk_cloud/baseplatform/

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.105:9001/eureka/
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yk1001/yk-config.git