server:
  port: 9101
   
logging:
  path: /yk/logs/yk_cloud/api/

spring:
  zipkin:
    base-url: http://192.168.0.105:9005
  sleuth:
    sampler:
      percentage: 1.0
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://${YK_DISCOVERY_SRV1_SERVICE_HOST}:${YK_DISCOVERY_SRV1_SERVICE_PORT}/eureka
    healthcheck:
      enabled: true
    instance:
      preferIpAddress: true

security:
  basic:
    enabled: false
  ignored: /noauth/**, /swagger**
  oauth2:
    client:
      client-id: yk
      client-secret: secret
      access-token-uri: http://192.168.0.105:9004/uaa/oauth/token
      grant-type: client_credentials
    resource:
      token-info-uri: http://192.168.0.105:9004/uaa/oauth/check_token