server:
  port: 9004
  context-path: /uaa
  
logging:
  path: /yk/logs/yk_cloud/baseplatform/
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.105:9001/eureka/
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30